"""Horos: classify a repository's token sinks and emit the reading boundary.

scan <root>    classify the tree; --json prints the boundary document,
               --write commits it to .horos/boundary.json atomically
check <root>   re-derive the boundary and name every drifted path
map <file.py>  print the file's skeleton instead of the file

Classification is fail-open: a file the rules cannot evidence stays readable
and earns no entry. The scanner stats every file but reads at most
PREFIX_BYTES of any of them, so a scan never costs more than a fraction of
what it saves.
"""

from pathlib import PurePosixPath
import argparse
import fnmatch
import hashlib
import json
import os
import subprocess
import sys

import languages

# The classifier's own reading limit. Raising it is an ask-first change once
# the tests pin it: every content rule below is defined against this prefix.
PREFIX_BYTES = 4096

# Geometry thresholds for data blobs and minified bundles. A small file is
# never a blob entry; whatever it costs, it costs almost nothing.
BLOB_MIN_BYTES = 16384
MINIFIED_MEAN_LINE_LENGTH = 400

# The maintainer's budgeted second pass: files above this size that the
# prefix leaves unclassified get two extra windows, middle and end.
LARGE_FILE_BYTES = 65536
WINDOW_BYTES = 2048

# Corroborating a candidate directory samples this many files, prefix-only,
# and needs three quarters of them to look minified, binary or generated.
DIR_SAMPLE_FILES = 8

LOCKFILE_NAMES = frozenset(
    {
        "bun.lockb",
        "Cargo.lock",
        "composer.lock",
        "flake.lock",
        "Gemfile.lock",
        "go.sum",
        "package-lock.json",
        "packages.lock.json",
        "Pipfile.lock",
        "pnpm-lock.yaml",
        "poetry.lock",
        "uv.lock",
        "yarn.lock",
    }
)

GENERATED_MARKERS = (
    "do not edit",
    "@generated",
    "code generated by",
    "auto-generated",
    "autogenerated",
    "automatically generated",
)

# A marker binds only on a comment-led line: a line whose first
# non-whitespace characters are one of these fixed, language-independent
# leaders. A generator declares itself in a comment banner; a marker inside
# a string literal, a call argument or a JSON value is data about markers,
# which is how this classifier once excluded its own source. `*` is in
# because block comments continue lines with it, the shape Javadoc and
# JSDoc banners take, and `--` because SQL, Haskell and Lua
# comment with it; `<!--` covers HTML and Markdown, `;` assembly, ini and
# Lisp, `%` TeX, MATLAB, Erlang and Prolog. The set is deliberately not
# per-extension: a fixed set is deterministic on any byte sequence and
# cannot be steered by a file's name.
COMMENT_LEADERS = ("#", "//", "/*", "*", "<!--", "--", ";", "%")


def marker_on_comment_led_line(lines):
    """The first generated-file marker sitting on a comment-led line, or None.

    Lines arrive as decoded text; the caller decides which lines are safe to
    judge (the window pass hands over only lines wholly contained in its
    window, so an offset landing mid-line cannot manufacture a match).
    """
    for line in lines:
        if not line.lstrip().startswith(COMMENT_LEADERS):
            continue
        lowered = line.lower()
        for marker in GENERATED_MARKERS:
            if marker in lowered:
                return marker
    return None


def contained_window_lines(window_text, offset, reached_end):
    """The lines wholly contained in a window read at the given offset.

    A window starting past byte zero is read blind: the byte before the
    offset is never seen, so the first fragment is always dropped. Usually
    that fragment is a partial line whose true start, and therefore leader,
    lies outside the window; when the offset happens to land exactly on a
    line's first byte, the drop instead costs that one whole line, a
    bounded, fail-open recall loss. The final fragment is dropped unless
    the window reached the end of the file, where the fragment is the
    file's real last line.
    """
    lines = window_text.split("\n")
    if offset > 0:
        lines = lines[1:]
    if not reached_end and lines:
        lines = lines[:-1]
    return lines

GENERATED_DIR_NAMES = frozenset({"build", "dist", "out", "storybook-static"})

VENDORED_DIR_NAMES = frozenset(
    {"bower_components", "node_modules", "third_party", "thirdparty", "vendor", "vendored"}
)

# Never walked, never listed: not source and not a sink worth recording.
SKIPPED_DIR_NAMES = frozenset({".git", ".horos", "__pycache__"})

# A content-addressed object store names each file by the digest of its own
# bytes. That makes it the one rule here whose evidence is recomputable from
# the file alone: nothing rests on a name, a convention or a marker string a
# repository could write to invite an exclusion. The digest either matches
# the name or the file stays readable.
CONTENT_ADDRESSED_ALGORITHMS = {
    "sha1": 40,
    "sha256": 64,
    "sha384": 96,
    "sha512": 128,
}

# The algorithm segment has to sit under one of these to count. Git's own
# object store deliberately matches neither layout: it names no algorithm,
# and its digests cover a header the raw bytes do not carry, so a git
# directory falls through to the other rules instead of verifying here.
CONTENT_ADDRESSED_PARENTS = frozenset({"blobs", "objects"})

# Verification is the only rule that reads a whole file rather than a
# bounded prefix, so the shape gate runs first and only a path already
# shaped like a content-addressed object is ever hashed. The read is
# chunked: these stores hold a tree's largest files by construction.
DIGEST_CHUNK_BYTES = 1 << 20


def _is_lower_hex(text):
    """True when every character is a lowercase hex digit."""
    return text != "" and all(c in "0123456789abcdef" for c in text)


def content_addressed_algorithm(relpath):
    """The digest algorithm this path's shape claims, or None.

    Two layouts count, both needing an <algorithm> segment directly under a
    'blobs' or 'objects' parent: flat, as an OCI image lays out
    blobs/sha256/<digest>, and sharded, as objects/sha256/<xx>/<digest>,
    where the shard must be a proper prefix of the digest it files. The name
    must be exactly the algorithm's hex width. Shape alone excludes nothing;
    it only decides which files are worth hashing.
    """
    parts = PurePosixPath(relpath).parts
    name = parts[-1]
    for index in range(len(parts) - 2, 0, -1):
        width = CONTENT_ADDRESSED_ALGORITHMS.get(parts[index])
        if width is None or parts[index - 1] not in CONTENT_ADDRESSED_PARENTS:
            continue
        if len(name) != width or not _is_lower_hex(name):
            continue
        shards = parts[index + 1 : -1]
        if shards:
            if len(shards) != 1 or len(shards[0]) >= width:
                continue
            if not name.startswith(shards[0]):
                continue
        return parts[index]
    return None


def digest_matches_name(fullpath, algorithm, name):
    """Hash the file's bytes and compare them with the name that claims them."""
    digest = hashlib.new(algorithm)
    with open(fullpath, "rb") as handle:
        for chunk in iter(lambda: handle.read(DIGEST_CHUNK_BYTES), b""):
            digest.update(chunk)
    return digest.hexdigest() == name


def read_prefix(path):
    """Return the first PREFIX_BYTES of the file, raw."""
    with open(path, "rb") as handle:
        return handle.read(PREFIX_BYTES)


# Git attributes are directory-scoped; each file is read up to this cap,
# per the maintainer's refinement specification.
ATTRIBUTES_CAP = 65536


def parse_attribute_file(path):
    """Parse one .gitattributes file for unnegated linguist-vendored and
    linguist-generated patterns, fail-open on anything unparseable."""
    rules = []
    if not os.path.isfile(path) or os.path.islink(path):
        return rules
    try:
        with open(path, "rb") as handle:
            text = handle.read(ATTRIBUTES_CAP).decode("utf-8", errors="replace")
    except OSError:
        return rules
    for line in text.splitlines():
        parts = line.split()
        if len(parts) < 2 or parts[0].startswith("#"):
            continue
        for category, attribute in (
            ("vendored", "linguist-vendored"),
            ("generated", "linguist-generated"),
        ):
            if attribute in parts[1:] or f"{attribute}=true" in parts[1:]:
                rules.append((parts[0].lstrip("/"), category, attribute))
    return rules


def gitattributes_rules(root):
    """The repository root's rules; nested files join during the walk."""
    return parse_attribute_file(os.path.join(root, ".gitattributes"))


def _ancestors_innermost_first(relpath):
    """The directory chain that scopes a path, innermost first, root last."""
    parts = PurePosixPath(relpath).parts[:-1]
    chain = []
    for i in range(len(parts), -1, -1):
        chain.append("/".join(parts[:i]) or ".")
    return chain


def match_attribute_scopes(scopes, relpath):
    """Match a path against every .gitattributes scope covering it,
    innermost scope first, so a deeper file overrides nothing outside its
    own directory but speaks first inside it."""
    for scope in _ancestors_innermost_first(relpath):
        rules = scopes.get(scope)
        if not rules:
            continue
        local = relpath if scope == "." else relpath[len(scope) + 1 :]
        for pattern, category, attribute in rules:
            candidates = [pattern]
            if pattern.endswith("/**"):
                candidates.append(pattern[: -len("/**")] + "/*")
            for candidate in candidates:
                if fnmatch.fnmatch(local, candidate) or fnmatch.fnmatch(
                    PurePosixPath(local).name, candidate
                ):
                    where = ".gitattributes" if scope == "." else f"{scope}/.gitattributes"
                    return category, f"{attribute} for {pattern!r} in {where}"
    return None


def match_gitattributes(rules, relpath):
    """Root-scope matching kept for callers holding a flat rule list."""
    return match_attribute_scopes({".": rules}, relpath)


# Leading bytes that name a binary format outright; more reliable than a
# null byte happening to appear inside the prefix.
FILE_SIGNATURES = (
    (b"\x89PNG\r\n\x1a\n", "png"),
    (b"\xff\xd8\xff", "jpeg"),
    (b"GIF87a", "gif"),
    (b"GIF89a", "gif"),
    (b"PK\x03\x04", "zip"),
    (b"%PDF", "pdf"),
    (b"\x00asm", "webassembly"),
    (b"wOFF", "woff"),
    (b"wOF2", "woff2"),
    (b"\x1f\x8b", "gzip"),
    (b"\x7fELF", "elf"),
    (b"OTTO", "opentype"),
    (b"RIFF", "riff"),
)


def match_signature(prefix):
    for magic, name in FILE_SIGNATURES:
        if prefix.startswith(magic):
            return name
    return None


def classify_content(name, size, prefix):
    """Content rules over the bounded prefix, most decisive first.

    Returns (category, evidence) or None. Order matters: a null byte makes
    every later text heuristic meaningless, so binary wins outright.
    """
    signature = match_signature(prefix)
    if signature is not None:
        return "binary", f"file signature {signature}", "hard"

    if b"\x00" in prefix:
        return "binary", "null byte in the first %d bytes" % PREFIX_BYTES, "candidate"

    text = prefix.decode("utf-8", errors="replace")
    lowered = text.lower()
    # SVG before the marker scan: a tool-stamped SVG is still an asset, and
    # asset is the more specific truth about it.
    if name.endswith(".svg") and "<svg" in lowered:
        return (
            "asset",
            f"svg root element in the first {PREFIX_BYTES} bytes",
            "candidate",
        )

    # The prefix starts at byte zero, so every line start it sees is real;
    # only the last line can be truncated, and truncation can lose a marker
    # (fail-open) but never invent one.
    marker = marker_on_comment_led_line(text.splitlines())
    if marker is not None:
        return (
            "generated",
            f"marker {marker!r} on a comment-led line in the first {PREFIX_BYTES} bytes",
            "hard",
        )

    if name.endswith(".map") and '"mappings"' in text:
        return (
            "generated",
            'sourcemap: name ends .map and prefix carries "mappings"',
            "hard",
        )

    if size >= BLOB_MIN_BYTES:
        newlines = prefix.count(b"\n")
        if newlines == 0:
            return (
                "blob",
                f"no newline in the first {PREFIX_BYTES} bytes of {size} bytes",
                "candidate",
            )
        if len(prefix) // (newlines + 1) > MINIFIED_MEAN_LINE_LENGTH:
            return (
                "blob",
                "mean line length above %d in the first %d bytes"
                % (MINIFIED_MEAN_LINE_LENGTH, PREFIX_BYTES),
                "candidate",
            )
    return None


def classify_windows(fullpath, name, size):
    """The selective second pass: two extra windows for a large file the
    prefix left unclassified. A marker found here is hard; geometry stays a
    candidate wherever it is found."""
    offsets = (size // 2, max(0, size - WINDOW_BYTES))
    with open(fullpath, "rb") as handle:
        for offset in offsets:
            handle.seek(offset)
            window = handle.read(WINDOW_BYTES)
            text = window.decode("utf-8", errors="replace")
            reached_end = offset + len(window) >= size
            marker = marker_on_comment_led_line(
                contained_window_lines(text, offset, reached_end)
            )
            if marker is not None:
                return (
                    "generated",
                    f"marker {marker!r} on a comment-led line in a "
                    f"{WINDOW_BYTES}-byte window at offset {offset}",
                    "hard",
                )
            newlines = window.count(b"\n")
            if newlines == 0:
                return (
                    "blob",
                    f"no newline in a {WINDOW_BYTES}-byte window at offset {offset} of {size} bytes",
                    "candidate",
                )
            if len(window) // (newlines + 1) > MINIFIED_MEAN_LINE_LENGTH:
                return (
                    "blob",
                    "mean line length above %d in a window at offset %d"
                    % (MINIFIED_MEAN_LINE_LENGTH, offset),
                    "candidate",
                )
    return None


def classify_file(root, relpath):
    """Classify one file; None means it stays readable.

    Raises OSError when the file cannot be statted or read, so the caller
    can count it as skipped rather than silently readable. Symlinks are
    refused here as well as in the walk: this function is public, and a
    caller handing it a link must not make the scanner read outside root.
    """
    fullpath = os.path.join(root, relpath)
    if os.path.islink(fullpath):
        return None
    name = PurePosixPath(relpath).name
    size = os.stat(fullpath).st_size

    # First, because it is the only rule that proves itself: a matching
    # digest is evidence no other reading of the file can overturn.
    algorithm = content_addressed_algorithm(relpath)
    if algorithm is not None and digest_matches_name(fullpath, algorithm, name):
        return {
            "path": relpath,
            "category": "content_addressed",
            "bytes": size,
            "evidence": f"{algorithm} digest of the file's own bytes equals its name",
            "grade": "hard",
        }

    if name in LOCKFILE_NAMES:
        return {
            "path": relpath,
            "category": "lockfile",
            "bytes": size,
            "evidence": f"lockfile name {name}",
            "grade": "hard",
        }

    if name.endswith(".sql") and "migrations" in PurePosixPath(relpath).parts[:-1]:
        return {
            "path": relpath,
            "category": "generated",
            "bytes": size,
            "evidence": "sql file under a migrations directory segment",
            "grade": "candidate",
        }

    prefix = read_prefix(fullpath)
    verdict = classify_content(name, size, prefix)
    if verdict is None and size > LARGE_FILE_BYTES:
        verdict = classify_windows(fullpath, name, size)
    if verdict is None:
        return None
    category, evidence, grade = verdict
    return {
        "path": relpath,
        "category": category,
        "bytes": size,
        "evidence": evidence,
        "grade": grade,
    }


def _suffix_of(name):
    """The name's last suffix, lowercased; a leading dot is not a suffix."""
    if "." in name[1:]:
        return "." + name.rsplit(".", 1)[1].lower()
    return "(no suffix)"


def _census_add(tally, name, size, in_boundary):
    if tally is None:
        return
    row = tally.setdefault(_suffix_of(name), {"files": 0, "bytes": 0, "boundary_bytes": 0})
    row["files"] += 1
    row["bytes"] += size
    if in_boundary:
        row["boundary_bytes"] += size


PACKAGE_MANAGER_DIRS = frozenset({"bower_components", "node_modules"})


def corroborate_directory(fulldir, dirname):
    """The second signal a candidate directory name needs before it excludes
    as hard: a known package-manager structure, or a deterministic sample of
    its first files looking overwhelmingly minified, binary or generated.
    Returns the corroborating evidence, or None."""
    if dirname in PACKAGE_MANAGER_DIRS:
        try:
            children = sorted(os.listdir(fulldir))
        except OSError:
            children = []
        for child in children:
            manifest = os.path.join(fulldir, child, "package.json")
            if os.path.isfile(manifest) and not os.path.islink(manifest):
                return f"package-manager structure ({child}/package.json)"

    sampled = []
    for dirpath, dirnames, filenames in os.walk(fulldir, followlinks=False):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIR_NAMES)
        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            sampled.append(fullpath)
            if len(sampled) >= DIR_SAMPLE_FILES:
                break
        if len(sampled) >= DIR_SAMPLE_FILES:
            break
    if not sampled:
        return None
    hits = 0
    for fullpath in sampled:
        try:
            size = os.stat(fullpath).st_size
            prefix = read_prefix(fullpath)
        except OSError:
            continue
        name = os.path.basename(fullpath)
        verdict = classify_content(name, max(size, BLOB_MIN_BYTES), prefix)
        if verdict is not None:
            hits += 1
    needed = max(1, (3 * len(sampled) + 3) // 4)
    if hits >= needed:
        return f"sample: {hits} of {len(sampled)} files minified, binary or generated"
    return None


def directory_entry(root, relpath, category, evidence, tally=None, grade="hard", universe=None):
    """Aggregate a vendored or generated directory into one entry."""
    total = 0
    files = 0
    for dirpath, dirnames, filenames in os.walk(
        os.path.join(root, relpath), followlinks=False
    ):
        dirnames[:] = sorted(d for d in dirnames if d not in SKIPPED_DIR_NAMES)
        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            if universe is not None:
                inner = os.path.relpath(fullpath, root).replace(os.sep, "/")
                if inner not in universe:
                    continue
            try:
                size = os.stat(fullpath).st_size
            except OSError:
                continue
            total += size
            files += 1
            _census_add(tally, filename, size, in_boundary=True)
    return {
        "path": relpath + "/",
        "category": category,
        "bytes": total,
        "files": files,
        "evidence": evidence,
        "grade": grade,
    }


def binding_directory_entry(
    root, relpath, category, evidence, tally=None, grade="hard", universe=None
):
    """One directory entry, or None when it would bind no tracked file.

    A directory holding nothing tracked is not a token sink: excluding it saves
    no bytes an agent would ever read, and emitting it makes the same check
    answer differently on two machines, since an ignored build directory or a
    stray worktree sits in one checkout and not the other. Fail-open still
    holds where git cannot answer: with no universe there is no tracked notion
    to test against, so the entry stands.

    Both passes go through here. A candidate is advisory rather than binding,
    but it is written to a file a maintainer commits, so it answers to the same
    rule: a finding nobody in another checkout can see is drift, not advice.
    """
    entry = directory_entry(
        root, relpath, category, evidence, tally, grade=grade, universe=universe
    )
    if universe is not None and entry["files"] == 0:
        return None
    return entry


def resolve_universe(root, include_untracked=False):
    """The file set a scan covers. Git-tracked by default so local build
    products and caches never contaminate a committed boundary; the
    filesystem walk is the fallback when git or the repository is absent.

    Returns (label, relpath_set_or_None)."""
    argv = ["git", "-C", root, "ls-files", "-z"]
    if include_untracked:
        argv += ["--cached", "--others", "--exclude-standard"]
    try:
        completed = subprocess.run(  # phylax: allow subprocess: fixed argv, no shell, cwd pinned by -C
            argv, capture_output=True, check=False
        )
    except OSError:
        return "filesystem", None
    if completed.returncode != 0:
        return "filesystem", None
    paths = completed.stdout.decode("utf-8", errors="replace").split("\0")
    label = "tracked+untracked" if include_untracked else "tracked"
    return label, {p for p in paths if p}


def _inside_scope(relpath, scope):
    """True when a root-relative path lies at or under the scope."""
    if scope is None:
        return True
    return relpath == scope or relpath.startswith(scope + "/")


def _leads_to_scope(relpath, scope):
    """True when a directory is the scope, inside it, or an ancestor of it.

    An ancestor is walked but never classified: its `.gitattributes` scopes the
    files below it, so skipping it would make a scoped check disagree with a
    whole-tree one about the same file.
    """
    if scope is None:
        return True
    return _inside_scope(relpath, scope) or scope.startswith(relpath + "/")


def scan_tree(root, census=False, include_untracked=False, scope=None):
    """Walk the tree and return entries plus the counts a quiet run reports.

    With census=True the same walk also tallies every file by suffix, so the
    census can never describe a different tree than the boundary does; the
    result gains a "census" key and nothing else changes.

    With scope set to a root-relative directory, only files at or under it are
    classified. The walk still begins at root, because the attribute files
    above the scope decide how the files inside it classify; those are read and
    counted separately. Whole subtrees outside the scope are pruned unvisited.
    """
    root = os.path.abspath(root)
    universe_label, universe = resolve_universe(root, include_untracked)
    scopes = {}
    tally = {} if census else None
    entries = []
    candidates = []
    walked = 0
    skipped_unreadable = 0
    outside_scope_listed = 0
    attribute_files_above_scope = 0

    for dirpath, dirnames, filenames in os.walk(root, followlinks=False):
        relative_dir = os.path.relpath(dirpath, root)
        posix_dir = "." if relative_dir == "." else relative_dir.replace(os.sep, "/")
        if ".gitattributes" in filenames:
            rules = parse_attribute_file(os.path.join(dirpath, ".gitattributes"))
            if rules:
                scopes[posix_dir] = rules
            if scope is not None and not _inside_scope(posix_dir, scope):
                attribute_files_above_scope += 1
        keep = []
        for dirname in sorted(dirnames):
            if dirname in SKIPPED_DIR_NAMES:
                continue
            child = os.path.join(dirpath, dirname)
            if os.path.islink(child):
                continue
            relpath = dirname if relative_dir == "." else f"{relative_dir}/{dirname}"
            relpath = relpath.replace(os.sep, "/")
            if not _leads_to_scope(relpath, scope):
                continue
            if not _inside_scope(relpath, scope):
                # On the path down to the scope: walk it, classify nothing.
                keep.append(dirname)
                continue
            named_category = None
            if dirname in VENDORED_DIR_NAMES:
                named_category = "vendored"
            elif dirname in GENERATED_DIR_NAMES:
                named_category = "generated"
            if named_category is not None:
                corroboration = corroborate_directory(child, dirname)
                if corroboration is not None:
                    entry = binding_directory_entry(
                        root,
                        relpath,
                        named_category,
                        f"directory name {dirname} corroborated by {corroboration}",
                        tally,
                        universe=universe,
                    )
                    if entry is not None:
                        entries.append(entry)
                    # Either way the subtree is pruned: an entry covers it, or
                    # it holds nothing tracked for the walk to classify.
                    continue
                # Name alone is a candidate signal; the subtree is walked
                # file by file instead of being excluded. The finding still has
                # to bind something in the universe, or it is a local artefact
                # the next checkout cannot reproduce.
                candidate = binding_directory_entry(
                    root,
                    relpath,
                    named_category,
                    f"directory name {dirname} alone, uncorroborated",
                    None,
                    grade="candidate",
                    universe=universe,
                )
                if candidate is not None:
                    candidates.append(candidate)
                keep.append(dirname)
                continue
            matched = match_attribute_scopes(scopes, relpath + "/")
            if matched is not None:
                entry = binding_directory_entry(
                    root, relpath, matched[0], matched[1], tally, universe=universe
                )
                if entry is not None:
                    entries.append(entry)
                continue
            keep.append(dirname)
        dirnames[:] = keep

        for filename in sorted(filenames):
            fullpath = os.path.join(dirpath, filename)
            if os.path.islink(fullpath):
                continue
            relpath = filename if relative_dir == "." else f"{relative_dir}/{filename}"
            relpath = relpath.replace(os.sep, "/")
            if universe is not None and relpath not in universe:
                continue
            if not _inside_scope(relpath, scope):
                # Listed by a directory the walk had to visit, and dropped
                # before any stat or read. Whole subtrees outside the scope are
                # pruned unvisited, so this counts only what the ancestor chain
                # put in front of the walk, never the tree's outside total.
                outside_scope_listed += 1
                continue
            walked += 1
            matched = match_attribute_scopes(scopes, relpath)
            if matched is not None:
                try:
                    size = os.stat(fullpath).st_size
                except OSError:
                    skipped_unreadable += 1
                    continue
                entries.append(
                    {
                        "path": relpath,
                        "category": matched[0],
                        "bytes": size,
                        "evidence": matched[1],
                        "grade": "hard",
                    }
                )
                _census_add(tally, filename, size, in_boundary=True)
                continue
            try:
                entry = classify_file(root, relpath)
            except OSError:
                skipped_unreadable += 1
                continue
            if entry is not None and entry["grade"] == "hard":
                entries.append(entry)
                _census_add(tally, filename, entry["bytes"], in_boundary=True)
            elif entry is not None:
                candidates.append(entry)
                _census_add(tally, filename, entry["bytes"], in_boundary=False)
            elif tally is not None:
                try:
                    _census_add(
                        tally, filename, os.stat(fullpath).st_size, in_boundary=False
                    )
                except OSError:
                    skipped_unreadable += 1

    entries.sort(key=lambda entry: entry["path"])
    candidates.sort(key=lambda entry: entry["path"])
    counts = {"files_walked": walked, "files_skipped_unreadable": skipped_unreadable}
    if scope is not None:
        counts["files_outside_scope_listed"] = outside_scope_listed
        counts["attribute_files_above_scope"] = attribute_files_above_scope
    for entry in entries:
        key = "bytes_" + entry["category"]
        counts[key] = counts.get(key, 0) + entry["bytes"]
    result = {
        "entries": entries,
        "candidates": candidates,
        "counts": counts,
        "universe": universe_label,
    }
    if scope is not None:
        result["scope"] = scope
    if tally is not None:
        result["census"] = tally
    return result


BOUNDARY_RELPATH = ".horos/boundary.json"
BOUNDARY_SCHEMA = 2
BOUNDARY_FIELDS = frozenset({"schema", "tool", "universe", "entries", "counts"})
CANDIDATES_RELPATH = ".horos/candidates.json"

# Printed after a boundary write, for the adopting repository's AGENTS.md or
# CLAUDE.md. This is the whole bridge to agents that have never heard of
# Horos: harnesses load those files at session start, so the discipline
# travels with the repository instead of with this skill.
ADOPTION_STANZA = """\
Paste this into the repository's AGENTS.md or CLAUDE.md so agents without
Horos inherit the boundary:

## Reading boundary

Before reading this repository broadly, consult `.horos/boundary.json`.
Every path listed there is a classified token sink carrying the evidence
that earned its entry; leave those paths unread unless the task demands
one. The boundary is fail-open: what it omits is merely unproven. It never
applies during security review; during any audit, review or incident work,
read as if no boundary exists.
"""


def boundary_document(result):
    """The committed artefact: schema-tagged, no timestamps, no absolute paths."""
    return {
        "schema": BOUNDARY_SCHEMA,
        "tool": "horos",
        "universe": result["universe"],
        "entries": result["entries"],
        "counts": result["counts"],
    }


def render(document):
    """One canonical byte form, so equal documents are equal files."""
    return json.dumps(document, indent=2, sort_keys=True) + "\n"


def _write_atomic(root, relpath, text):
    """Write atomically: a killed run leaves the old artefact or the new one."""
    directory = os.path.join(root, os.path.dirname(relpath))
    os.makedirs(directory, exist_ok=True)
    final = os.path.join(root, relpath)
    # Per-process name: two concurrent scans must not unlink each other's
    # half-written temporary in the finally block below.
    temporary = f"{final}.{os.getpid()}.tmp"
    try:
        with open(temporary, "w", encoding="utf-8") as handle:
            handle.write(text)
        os.replace(temporary, final)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def write_boundary(root, document):
    _write_atomic(root, BOUNDARY_RELPATH, render(document))


def candidates_document(result):
    """The advisory report: candidate findings a maintainer can promote to a
    repository-specific rule. Candidates never bind an agent."""
    counts = {}
    for entry in result["candidates"]:
        key = "bytes_" + entry["category"]
        counts[key] = counts.get(key, 0) + entry["bytes"]
    return {
        "schema": BOUNDARY_SCHEMA,
        "tool": "horos",
        "universe": result["universe"],
        "entries": result["candidates"],
        "counts": counts,
    }


def write_candidates(root, document):
    _write_atomic(root, CANDIDATES_RELPATH, render(document))


CENSUS_RELPATH = ".horos/census.json"
CENSUS_SCHEMA = 1


def census_document(result):
    """The per-filetype breakdown: exact integers, sorted rows, no clocks."""
    rows = [
        {"suffix": suffix, **row} for suffix, row in result["census"].items()
    ]
    rows.sort(key=lambda row: (-row["bytes"], row["suffix"]))
    return {
        "schema": CENSUS_SCHEMA,
        "tool": "horos",
        "total_files": sum(row["files"] for row in rows),
        "total_bytes": sum(row["bytes"] for row in rows),
        "rows": rows,
    }


def write_census(root, document):
    _write_atomic(root, CENSUS_RELPATH, render(document))


class BoundaryFormatError(ValueError):
    """A boundary whose JSON cannot identify one unambiguous document."""


def _object_without_duplicate_keys(pairs):
    found = {}
    for key, value in pairs:
        if key in found:
            raise BoundaryFormatError("duplicate JSON key %r" % key)
        found[key] = value
    return found


def load_boundary(root):
    with open(os.path.join(root, BOUNDARY_RELPATH), encoding="utf-8") as handle:
        document = json.load(handle, object_pairs_hook=_object_without_duplicate_keys)
    if not isinstance(document, dict):
        raise BoundaryFormatError("boundary must be a JSON object")
    return document


def json_equal(left, right):
    """Compare JSON values recursively without Python's numeric type aliases."""
    if type(left) is not type(right):
        return False
    if isinstance(left, dict):
        if len(left) != len(right):
            return False
        unmatched = list(right.items())
        for left_key, left_value in left.items():
            for index, (right_key, right_value) in enumerate(unmatched):
                if not json_equal(left_key, right_key):
                    continue
                if not json_equal(left_value, right_value):
                    return False
                unmatched.pop(index)
                break
            else:
                return False
        return not unmatched
    if isinstance(left, list):
        return len(left) == len(right) and all(
            json_equal(left_item, right_item)
            for left_item, right_item in zip(left, right)
        )
    return left == right


def diff_documents(committed, fresh):
    """Name every drifted path; a symmetric compare, so a committed entry the
    tree no longer evidences drifts exactly like a new sink the boundary lacks.
    """
    old = {entry["path"]: entry for entry in committed.get("entries", [])}
    new = {entry["path"]: entry for entry in fresh.get("entries", [])}
    drifted = []
    for path in sorted(set(old) | set(new)):
        if path not in new:
            drifted.append((path, "in the boundary but no longer evidenced by the tree"))
        elif path not in old:
            drifted.append((path, "evidenced by the tree but missing from the boundary"))
        elif not json_equal(old[path], new[path]):
            drifted.append((path, "entry changed: %s -> %s" % (old[path], new[path])))
    return drifted


def diff_boundary_documents(committed, fresh):
    """Compare every canonical field of a whole-root boundary document.

    Entry drift stays path-granular.  The other canonical fields describe the
    scan itself, so a mismatch is named against the boundary artefact.  Scoped
    checks deliberately do not call this function: their fresh counts and
    universe cover only the admitted subtree and make no whole-tree claim.
    """
    drifted = []
    committed_fields = set(committed)
    fresh_fields = set(fresh)
    if committed_fields != BOUNDARY_FIELDS or fresh_fields != BOUNDARY_FIELDS:
        drifted.append(
            (
                "%s#fields" % BOUNDARY_RELPATH,
                "closed top-level field set changed: %s -> %s; expected %s"
                % (
                    sorted(committed_fields),
                    sorted(fresh_fields),
                    sorted(BOUNDARY_FIELDS),
                ),
            )
        )
    for field in ("schema", "tool", "universe", "counts"):
        old = committed.get(field)
        new = fresh.get(field)
        if not json_equal(old, new):
            drifted.append(
                (
                    "%s#%s" % (BOUNDARY_RELPATH, field),
                    "field changed: %r -> %r" % (old, new),
                )
            )
    entry_drift = diff_documents(committed, fresh)
    if not json_equal(committed.get("entries"), fresh.get("entries")):
        if entry_drift:
            drifted.extend(entry_drift)
        else:
            drifted.append(
                (
                    "%s#entries" % BOUNDARY_RELPATH,
                    "canonical entry order or multiplicity changed",
                )
            )
    if not drifted and not json_equal(committed, fresh):
        drifted.append(
            (
                "%s#document" % BOUNDARY_RELPATH,
                "canonical boundary document changed",
            )
        )
    return drifted


def git_worktree_root(path):
    """The worktree root git reports for a path, or None when git cannot say."""
    try:
        completed = subprocess.run(  # phylax: allow subprocess: fixed argv, no shell, cwd pinned by -C
            ["git", "-C", path, "rev-parse", "--show-toplevel"],
            capture_output=True,
            check=False,
        )
    except OSError:
        return None
    if completed.returncode != 0:
        return None
    top = completed.stdout.decode("utf-8", errors="replace").strip()
    return os.path.realpath(top) if top else None


def _within(path, ancestor):
    return path == ancestor or path.startswith(ancestor + os.sep)


def resolve_boundary_root(target):
    """Find the one boundary that governs a path.

    Returns ((boundary root, scope), None) or (None, reason). The search walks
    upward from the target to the nearest committed boundary and stops at the
    worktree root git reports, so a boundary planted above a repository cannot
    capture a check made inside it. The target is resolved once, up front, and
    no symlink is followed during the search; a symlink that leaves the
    worktree is refused rather than resolved into a different tree.
    """
    given = os.path.abspath(target)
    resolved = os.path.realpath(given)
    if not os.path.isabs(target):
        # A relative path means "inside the repository I am working in", so
        # anything that resolves out of it is refused rather than answered
        # from another tree's boundary. This covers `..`, a symlinked final
        # component and a symlinked intermediate one alike, which a check on
        # the given path alone does not: `git -C` resolves symlinks before it
        # answers, so a path with a symlink in the middle would otherwise
        # report the far repository as its own worktree.
        here = git_worktree_root(os.getcwd())
        if here is not None and not _within(resolved, here):
            return None, f"path leaves the worktree at {here}"
    elif os.path.islink(given):
        parent_root = git_worktree_root(os.path.dirname(given))
        if parent_root is not None and not _within(resolved, parent_root):
            return None, f"symlink leaves the worktree at {parent_root}"
    if not os.path.isdir(resolved):
        return None, f"not a directory: {target}"
    limit = git_worktree_root(resolved)
    current = resolved
    while True:
        if os.path.isfile(os.path.join(current, BOUNDARY_RELPATH)):
            scope = os.path.relpath(resolved, current).replace(os.sep, "/")
            return (current, scope), None
        if limit is not None and current == limit:
            return None, f"no boundary between {resolved} and the worktree root {limit}"
        parent = os.path.dirname(current)
        if parent == current:
            return None, f"no boundary at or above {resolved}"
        current = parent


def entries_under(document, scope, key="entries"):
    """The slice of a boundary document that lies at or under the scope."""
    return [
        entry for entry in document.get(key, [])
        if _inside_scope(entry["path"].rstrip("/"), scope)
    ]


def check_scope(boundary_root, scope, out=None):
    """Admit a descendant scope against the one boundary above it.

    Exit 0 admits the scope, 1 means hard drift inside it. A green scoped check
    says nothing about the rest of the repository, and the output says so in
    those words: a local pass read as a global one is the failure this phrasing
    exists to prevent.
    """
    out = out if out is not None else sys.stdout
    try:
        committed = load_boundary(boundary_root)
    except FileNotFoundError:
        print(f"horos: no boundary at {BOUNDARY_RELPATH}; run scan --write", file=out)
        return 2
    except (OSError, json.JSONDecodeError, BoundaryFormatError) as error:
        print(f"horos: unreadable boundary: {error}", file=out)
        return 2
    include_untracked = committed.get("universe") == "tracked+untracked"
    result = scan_tree(boundary_root, include_untracked=include_untracked, scope=scope)
    fresh = boundary_document(result)
    drifted = diff_documents(
        {"entries": entries_under(committed, scope)},
        {"entries": entries_under(fresh, scope)},
    )
    candidate_count = len(entries_under(candidates_document(result), scope))
    print(f"boundary root: {boundary_root}", file=out)
    print(f"scope: {scope}", file=out)
    for path, reason in drifted:
        print(f"drift: {path}: {reason}", file=out)
    print(f"hard boundary: {'drifted' if drifted else 'matches'}", file=out)
    print(f"candidates: {candidate_count} findings, advisory", file=out)
    print("outside-scope drift: not evaluated", file=out)
    counts = result["counts"]
    print(
        "counters: classified {}, listed outside scope {}, "
        "attribute files above scope {}".format(
            counts["files_walked"],
            counts["files_outside_scope_listed"],
            counts["attribute_files_above_scope"],
        ),
        file=out,
    )
    return 1 if drifted else 0


def check_scope_or_tree(target, out=None):
    """Check whatever the path names: the whole tree, or one scope inside it.

    This is the whole of the `check` command, so the dispatch a caller gets is
    the dispatch the tests drive.
    """
    out = out if out is not None else sys.stdout
    resolved, reason = resolve_boundary_root(target)
    if resolved is None:
        print(f"horos: {reason}", file=out)
        return 2
    boundary_root, scope = resolved
    if scope == ".":
        return check_tree(boundary_root, out=out)
    return check_scope(boundary_root, scope, out=out)


def check_tree(root, out=None):
    out = out if out is not None else sys.stdout
    try:
        committed = load_boundary(root)
    except FileNotFoundError:
        print(f"horos: no boundary at {BOUNDARY_RELPATH}; run scan --write", file=out)
        return 2
    except (OSError, json.JSONDecodeError, BoundaryFormatError) as error:
        print(f"horos: unreadable boundary: {error}", file=out)
        return 2
    include_untracked = committed.get("universe") == "tracked+untracked"
    result = scan_tree(root, include_untracked=include_untracked)
    fresh = boundary_document(result)
    fresh_candidates = candidates_document(result)
    candidate_drift = []
    try:
        with open(os.path.join(root, CANDIDATES_RELPATH), encoding="utf-8") as handle:
            committed_candidates = json.load(handle)
    except (OSError, json.JSONDecodeError):
        committed_candidates = None
    if committed_candidates is not None:
        candidate_drift = diff_documents(committed_candidates, fresh_candidates)
    # Candidate classification is advisory, but the whole-root boundary's raw
    # canonical metadata is not. Adding or removing any tracked file changes
    # files_walked independently of whether that file is only a candidate.
    drifted = diff_boundary_documents(committed, fresh)
    for path, reason in candidate_drift:
        print(f"candidate drift: {path}: {reason}", file=out)
    if not drifted:
        print("boundary matches the tree", file=out)
        return 0
    for path, reason in drifted:
        print(f"drift: {path}: {reason}", file=out)
    print(f"{len(drifted)} path(s) drifted", file=out)
    return 1


def map_file(path, out=None):
    """Print a file's skeleton via its language extractor; orientation
    without the read."""
    out = out if out is not None else sys.stdout
    extractor = None
    for suffix in sorted(languages.EXTRACTORS, key=len, reverse=True):
        if path.endswith(suffix):
            extractor = languages.EXTRACTORS[suffix]
            break
    if extractor is None:
        print(f"horos: map supports {languages.supported()}, not {path}", file=out)
        return 2
    try:
        with open(path, "rb") as handle:
            source = handle.read().decode("utf-8", errors="replace")
    except OSError as error:
        print(f"horos: cannot read {path}: {error}", file=out)
        return 2
    return extractor(path, source, out)


def main(argv=None):
    parser = argparse.ArgumentParser(prog="horos", description=__doc__)
    subparsers = parser.add_subparsers(dest="command", required=True)
    scan = subparsers.add_parser("scan", help="classify a tree")
    scan.add_argument("root", help="directory to scan")
    scan.add_argument(
        "--json", action="store_true", help="print the boundary document"
    )
    scan.add_argument(
        "--write", action="store_true", help=f"write {BOUNDARY_RELPATH} atomically"
    )
    scan.add_argument(
        "--include-untracked",
        action="store_true",
        help="widen the universe to untracked-but-not-ignored files",
    )
    scan.add_argument(
        "--census",
        action="store_true",
        help=f"per-filetype breakdown; with --write it goes to {CENSUS_RELPATH}",
    )
    checker = subparsers.add_parser("check", help="verify the committed boundary")
    checker.add_argument("root", help="directory to check")
    mapper = subparsers.add_parser("map", help="print a Python file's skeleton")
    mapper.add_argument("file", help="Python file to map")
    args = parser.parse_args(argv)

    if args.command == "map":
        return map_file(args.file)

    if not os.path.isdir(args.root):
        print(f"horos: not a directory: {args.root}", file=sys.stderr)
        return 2

    if args.command == "check":
        return check_scope_or_tree(args.root)

    result = scan_tree(
        args.root, census=args.census, include_untracked=args.include_untracked
    )

    if args.census:
        document = census_document(result)
        if args.write:
            write_census(args.root, document)
        if args.json:
            sys.stdout.write(render(document))
        else:
            total = document["total_bytes"] or 1
            for row in document["rows"]:
                share = 100 * row["bytes"] / total
                print(
                    f"{row['suffix']}  files={row['files']}  bytes={row['bytes']}"
                    f"  share={share:.1f}%  boundary_bytes={row['boundary_bytes']}"
                )
            print(f"total: {document['total_files']} files, {document['total_bytes']} bytes")
        return 0

    document = boundary_document(result)
    advisory = candidates_document(result)
    if args.write:
        write_boundary(args.root, document)
        write_candidates(args.root, advisory)
    if args.json:
        sys.stdout.write(render(document))
    else:
        for key, value in sorted(document["counts"].items()):
            print(f"{key}: {value}")
        print(f"entries: {len(document['entries'])}")
        print(f"candidates: {len(advisory['entries'])}")
        if args.write:
            print()
            print(ADOPTION_STANZA, end="")
    return 0


if __name__ == "__main__":
    sys.exit(main())
